print("*******BIO DATA*********")
print("______________________________")
name=(input("Name :"))
age=int(input("Age :"))
bloodgroup=(input("Blood Group :"))
address=(input("Address :"))
native=(input("Native :"))
pincode=int(input("Pin code :"))
phonenumber=int(input("Phone number :"))
eamil=(input("Email :"))
print("_________________________")
print("Family")
fathername=(input("Father name :"))
mpthername=(input("Mother name :"))
sistername=(input("sister name :"))
print("___________________________")
print("Schooling")
hsc=(input("HSC :"))
sslc=(input("Sslc :"))
collage=(input("Collage :"))
print("______________________")
print("Skills  :Good at programming")
print("        :Python programming")
print("_____________________________")
hobby=(input("Hobby :"))
print("______________________________")
print("**********THANK YOU**********")
